# Generated by Django 3.2 on 2023-12-06 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=datetime.datetime(2023, 12, 6, 12, 31, 41, 587717, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
