# Generated by Django 3.2 on 2023-12-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20231213_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='name',
            new_name='country',
        ),
    ]
